---
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
- name: Extract artifact.tar.gz
  ansible.builtin.unarchive:
    src: /root/artifact.tar.gz
    dest: /

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: start the application
  command: pm2 start npm -- start
